CREATE TABLE `merchant` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` varchar(30) NOT NULL COMMENT '商户名称',
  `contact_name` varchar(30) NOT NULL COMMENT '联系人姓名',
  `contact_mobile` varchar(30) NOT NULL COMMENT '联系人电话',
  `start_hours` time NOT NULL COMMENT '营业时间(开始时间）',
  `end_hours` varchar(30) NOT NULL COMMENT '营业时间(结束时间)',
  `province` varchar(30) NOT NULL COMMENT '所属省份（000001）',
  `city` varchar(30) NOT NULL COMMENT '所属市（000001001）',
  `area` varchar(30) NOT NULL COMMENT '所属区（000001001001）',
  `address` varchar(30) NOT NULL COMMENT '详细地址',
  `logo` varchar(30) NOT NULL COMMENT '门店Logo（图片url，单张）',
  `out_image` varchar(30) NOT NULL COMMENT '门店外景照片（图片url,url,url）',
  `inner_image` varchar(30) NOT NULL COMMENT '门店内景照片（url,url,url,url）',
  `id_card_front_image` varchar(30) DEFAULT NULL COMMENT '身份证正面照',
  `id_card_back_image` varchar(30) DEFAULT NULL COMMENT '身份证反面照',
  `business_license` varchar(30) DEFAULT NULL COMMENT '营业执照（图片上传）',
  `industry_license` varchar(30) DEFAULT NULL COMMENT '行业许可证',
  `state` int(1) NOT NULL DEFAULT '0' COMMENT '审核状态（0：未审核，1：通过；2：不通过）',
  `longitude` double NOT NULL DEFAULT '0' COMMENT '经度',
  `latitude` double NOT NULL DEFAULT '0' COMMENT '纬度',
  `password` varchar(35) DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商户信息表';